### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by kandanaoki** [kandanaoki/protospace-35832#1]
https://protospace-35832.herokuapp.com/

**Comment by miyu-yamamoto** [comment]
@kandanaoki さん、お待たせいたしました。
動作を確認したところ修正いただきたい箇所がございました。
以下をご確認ください。

[修正依頼箇所]
- [ ] **コメントフォームを空のまま投稿しようとすると、投稿できずにそのページに留まるようにしましょう。**
現状、エラー画面が表示されてしまいます。

<img width="669" alt="スクリーンショット 2021-05-31 10 11 04" src="https://user-images.githubusercontent.com/59544869/120126848-89083a00-c1f8-11eb-8349-c378788ccae5.png">

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7
